---
- include: "{{ os_include_item }}"
  with_first_found:
    - "ppa-{{ ansible_distribution | lower }}.yml"
    - "ppa-{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: os_include_item

- name: adding cassandra repository
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 30x main
    state: present
    filename: cassandra
  register: dsc
  until: dsc|success
  retries: 5
  delay: 5

- name: add cassandra key
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: A278B781FE4B2BDA
  register: dsc_key
  until: dsc_key|success
  retries: 5
  delay: 5
